PRAGMA foreign_keys = ON;

CREATE TABLE Usuarios (
    RVP1 INTEGER PRIMARY KEY,
    Nombre TEXT NOT NULL,
    Buzón TEXT UNIQUE NOT NULL,
    wlst TEXT NOT NULL,
    Tipo_de_usuario TEXT NOT NULL,
    Teléfono TEXT UNIQUE NOT NULL
);

CREATE TABLE Tonos (
    RVP8 INTEGER PRIMARY KEY,
    Nombre_del_Tono TEXT NOT NULL
);

CREATE TABLE Configuración (
    RVP7 INTEGER PRIMARY KEY,
    RVP1 INTEGER NOT NULL,
    RVP8 INTEGER NOT NULL,
    Alertas_visuales BOOLEAN NOT NULL,
    Tema_app TEXT NOT NULL,
    FOREIGN KEY (RVP1) REFERENCES Usuarios(RVP1) ON DELETE CASCADE,
    FOREIGN KEY (RVP8) REFERENCES Tonos(RVP8) ON DELETE SET NULL
);

CREATE TABLE Contactos_de_Confianza (
    RVP5 INTEGER PRIMARY KEY,
    Nombre_Contacto TEXT NOT NULL,
    Teléfono_Contacto TEXT UNIQUE NOT NULL
);

CREATE TABLE Contactos_Asociados (
    RVP1 INTEGER NOT NULL,
    RVP5 INTEGER NOT NULL,
    PRIMARY KEY (RVP1, RVP5),
    FOREIGN KEY (RVP1) REFERENCES Usuarios(RVP1) ON DELETE CASCADE,
    FOREIGN KEY (RVP5) REFERENCES Contactos_de_Confianza(RVP5) ON DELETE CASCADE
);

CREATE TABLE Sesiones_de_Manejo (
    RVP2 INTEGER PRIMARY KEY,
    RVP1 INTEGER NOT NULL,
    Fecha_Inicio DATE NOT NULL,
    Hora_Inicio TIME NOT NULL,
    Fecha_Fin DATE NOT NULL,
    Hora_Fin TIME NOT NULL,
    FOREIGN KEY (RVP1) REFERENCES Usuarios(RVP1) ON DELETE CASCADE
);

CREATE TABLE Alertas_Generadas (
    RVP3 INTEGER PRIMARY KEY,
    RVP2 INTEGER NOT NULL,
    Fecha DATE NOT NULL,
    Hora TIME NOT NULL,
    Ubicación TEXT NOT NULL,
    Contenido TEXT NOT NULL,
    FOREIGN KEY (RVP2) REFERENCES Sesiones_de_Manejo(RVP2) ON DELETE CASCADE
);

CREATE TABLE Destinatarios_de_Alertas (
    RVP3 INTEGER NOT NULL,
    RVP5 INTEGER NOT NULL,
    PRIMARY KEY (RVP3, RVP5),
    FOREIGN KEY (RVP3) REFERENCES Alertas_Generadas(RVP3) ON DELETE CASCADE,
    FOREIGN KEY (RVP5) REFERENCES Contactos_de_Confianza(RVP5) ON DELETE CASCADE
);

CREATE TABLE Modo_Padres (
    RVP9 INTEGER PRIMARY KEY,
    RVP1 INTEGER NOT NULL,
    RVP1_H INTEGER NOT NULL,
    Nombre_hijo TEXT NOT NULL,
    Telefono_hijo TEXT UNIQUE NOT NULL,
    FOREIGN KEY (RVP1) REFERENCES Usuarios(RVP1) ON DELETE CASCADE
);

