# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Bd connect

on:
  push:
    branches: [ "API" ]
  pull_request:
    branches: [ "API" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout código
      uses: actions/checkout@v4
      with:
        ref: API
    - name: Configurar Python
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"      
    - name: Ejecutar script
      run: python testeo.py
